name: Bogazici-DevSecOps-Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}   # İstersen Actions > Run workflow ile manuel tetikleyebil

jobs:
  build-and-syft:
    name: Build & SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docker imajını mevcut Dockerfile ile build et
      - name: Build Docker image
        run: |
          docker build -t juice-shop:${{ github.sha }} .

      # Syft ile imajdan SPDX SBOM üret
      - name: Syft SBOM Scan (image → SPDX)
        uses: anchore/sbom-action@v0
        with:
          image: "juice-shop:${{ github.sha }}"
          format: "spdx-json"
          output-file: "sbom.spdx.json"


           # Semgrep'i default güvenlik kurallarıyla (OWASP benzeri) çalıştır
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default            # İstersen p/javascript p/typescript vb. yapabilirsin
          generateSarif: true
          sarifFile: semgrep.sarif
          enable-metrics: false        # Telemetry kapalı (opsiyonel)

      # Üretilen SARIF'i GitHub Security -> Code scanning alerts'e yükle
      - name: Upload Semgrep SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
